[character]
error_symbol = "[>](bold red)"
success_symbol = "[>](bold green)"
# vicmd_symbol = "[❮❮](bold yellow)"

[package]
disabled = true

[git_status]
disabled = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 15
truncate_to_repo = false
truncation_symbol = "''''"

[username]
show_always = true
